CREATE TABLE IF NOT EXISTS Song (
  id INTEGER CONSTRAINT PK_SONG PRIMARY KEY AUTOINCREMENT NOT NULL,
  title VARCHAR(1024) NOT NULL,
  artist VARCHAR(1024) NOT NULL,
  source_url VARCHAR(1024),
  
  content TEXT NOT NULL
);